id: P006778
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:22:26.873830
source_metadata:
  id: bdr:W3CN4066
  title: བསང་གི་ཆོ་ག་བདེ་ལེགས་ཀུན་འབྱུང་།
  author: ''
  volumes:
    dfd078ddc9d34708af32250037ba908c:
      image_group_id: I3CN6491
      title: ''
      volume_number: 1
      total_pages: 716
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
